### ISSUE TITLE
Question about italic "W" character

### ISSUE THREAD

**Issue by AB1908** [edwardtufte/et-bembo#26]
The capital "W" seems a bit odd to me. Having no knowledge of typography, I'd appreciate if anyone could explain what's happening here. Is this a design choice?

<img width="165" alt="image" src="https://user-images.githubusercontent.com/14124383/130457159-14e4cbb2-6fd8-4b2c-a3ea-84dcb039ec6f.png">

**Comment by RuixiZhang42** [comment]
Are you asking about the (over-)slant of the italic uppercase “W”? That would be a design choice.

For example, [*Equity*](https://mbtype.com/fonts/equity/) (designed by Matthew Butterick), which is based on [*Ehrhardt*](https://en.wikipedia.org/wiki/Ehrhardt_(typeface)), also features what you’d call “overly slanted uppercase A, V, and W” in its italic:
![Equity-AVW](https://user-images.githubusercontent.com/39968857/130826134-552f2793-05a5-4edb-8a83-0a10ced02fc0.png)

But these slants in *ET&nbsp;Book* and *Equity* are nothing compared to [*Rosart*](https://camelot-typefaces.com/rosart)’s more aggressive tilt:
![Rosart-AVW](https://user-images.githubusercontent.com/39968857/130826174-cbe623d5-2d50-4b13-86db-90f7e5d93d8d.png)

Bethany Heck wrote a piece about *Rosart* in her [*Font Review Journal*](https://fontreviewjournal.com/rosart/), where she mentioned this “aggressive forward tilt and ‘wind sheared’ aesthetic”.

**Comment by RuixiZhang42** [comment]
**Side note.** Admittedly, these heavily slanted forms can look odd to our 21st-century eyes, but I&nbsp;think this is only because many digital fonts we see today don’t feature these forms (so we are simply not used to how they look). However, if you look at the printed materials prior to the desktop-publishing era, then you can find many examples of such slanted forms.

For example, here is the caption to the illustration *Disappearing Bicyclist* (1906; source: https://www.geogebra.org/m/hypuahfc):
![disappearing-bicyclist](https://user-images.githubusercontent.com/39968857/130841995-857a2225-9cb7-49d5-9bf1-52dead6ce0bc.png)

Then there’s *Writing & illuminating, & lettering* (Johnston, 1906, p.&nbsp;269; source: https://archive.org/details/writingillumina00john):
![WIL-p269](https://user-images.githubusercontent.com/39968857/130842034-f52dff32-5f44-489d-af39-ebd708a358ba.png)

**Comment by AB1908** [comment]
Very fascinating insight. Thank you for taking the time to explain. Would you have any recommendations for books/journals on typography?
